# Generated by Django 4.1.5 on 2023-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_pessoa_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default=1, upload_to='foto'),
            preserve_default=False,
        ),
    ]
